---
version: 2.1

orbs:
  orb-tools: circleci/orb-tools@10
  ansible: cloudalchemy/ansible@<<pipeline.parameters.dev-orb-version>>

parameters:
  run-integration-tests:
    description: An internal flag to prevent integration test from running before a development version has been created.
    type: boolean
    default: false
  dev-orb-version:
    description: >
      The development version of the orb to test.
      This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond with the specific version created by the commit and should not be edited.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"

workflows:
  integration-test_deploy:
    jobs:
      - orb-tools/dev-promote-prod-from-commit-subject:
          add-pr-comment: false
          fail-if-semver-not-indicated: false
          filters:
            branches:
              only: master
          orb-name: cloudalchemy/ansible
          publish-version-tag: false
    when: << pipeline.parameters.run-integration-tests >>
  test-pack-ansible:
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          source-dir: ansible
      - orb-tools/publish-dev:
          context: orb
          orb-name: cloudalchemy/ansible
          requires:
            - orb-tools/lint
            - orb-tools/pack
      - orb-tools/trigger-integration-tests-workflow:
          context: orb
          name: trigger-integration-dev
          requires:
            - orb-tools/publish-dev
    unless: << pipeline.parameters.run-integration-tests >>
